// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: course/course.proto

package course

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	common "github.com/abu-umair/be-lms-go/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCourseRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address            string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	ImageFileName      string                 `protobuf:"bytes,4,opt,name=image_file_name,json=imageFileName,proto3" json:"image_file_name,omitempty"`
	Slug               *string                `protobuf:"bytes,5,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	CategoryId         *string                `protobuf:"bytes,6,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	CourseType         *string                `protobuf:"bytes,7,opt,name=course_type,json=courseType,proto3,oneof" json:"course_type,omitempty"`
	Title              *string                `protobuf:"bytes,8,opt,name=title,proto3,oneof" json:"title,omitempty"`
	SeoDescription     *string                `protobuf:"bytes,9,opt,name=seo_description,json=seoDescription,proto3,oneof" json:"seo_description,omitempty"`
	Duration           *string                `protobuf:"bytes,10,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	Timezone           *string                `protobuf:"bytes,11,opt,name=timezone,proto3,oneof" json:"timezone,omitempty"`
	Thumbnail          *string                `protobuf:"bytes,12,opt,name=thumbnail,proto3,oneof" json:"thumbnail,omitempty"`
	DemoVideoStorage   *string                `protobuf:"bytes,13,opt,name=demo_video_storage,json=demoVideoStorage,proto3,oneof" json:"demo_video_storage,omitempty"`
	DemoVideoSource    *string                `protobuf:"bytes,14,opt,name=demo_video_source,json=demoVideoSource,proto3,oneof" json:"demo_video_source,omitempty"`
	Description        *string                `protobuf:"bytes,15,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Capacity           *int64                 `protobuf:"varint,16,opt,name=capacity,proto3,oneof" json:"capacity,omitempty"`
	Price              *string                `protobuf:"bytes,17,opt,name=price,proto3,oneof" json:"price,omitempty"`
	Discount           *string                `protobuf:"bytes,18,opt,name=discount,proto3,oneof" json:"discount,omitempty"`
	Certificate        *string                `protobuf:"bytes,19,opt,name=certificate,proto3,oneof" json:"certificate,omitempty"`
	Gna                *string                `protobuf:"bytes,20,opt,name=gna,proto3,oneof" json:"gna,omitempty"`
	MessageForReviewer *string                `protobuf:"bytes,21,opt,name=message_for_reviewer,json=messageForReviewer,proto3,oneof" json:"message_for_reviewer,omitempty"`
	IsApproved         *string                `protobuf:"bytes,22,opt,name=is_approved,json=isApproved,proto3,oneof" json:"is_approved,omitempty"`
	Status             *string                `protobuf:"bytes,23,opt,name=status,proto3,oneof" json:"status,omitempty"`
	CourseLevelId      *string                `protobuf:"bytes,24,opt,name=course_level_id,json=courseLevelId,proto3,oneof" json:"course_level_id,omitempty"`
	CourseLanguageId   *string                `protobuf:"bytes,25,opt,name=course_language_id,json=courseLanguageId,proto3,oneof" json:"course_language_id,omitempty"`
	UserId             *string                `protobuf:"bytes,26,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateCourseRequest) Reset() {
	*x = CreateCourseRequest{}
	mi := &file_course_course_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseRequest) ProtoMessage() {}

func (x *CreateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_course_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseRequest.ProtoReflect.Descriptor instead.
func (*CreateCourseRequest) Descriptor() ([]byte, []int) {
	return file_course_course_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCourseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateCourseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCourseRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateCourseRequest) GetImageFileName() string {
	if x != nil {
		return x.ImageFileName
	}
	return ""
}

func (x *CreateCourseRequest) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

func (x *CreateCourseRequest) GetCategoryId() string {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return ""
}

func (x *CreateCourseRequest) GetCourseType() string {
	if x != nil && x.CourseType != nil {
		return *x.CourseType
	}
	return ""
}

func (x *CreateCourseRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *CreateCourseRequest) GetSeoDescription() string {
	if x != nil && x.SeoDescription != nil {
		return *x.SeoDescription
	}
	return ""
}

func (x *CreateCourseRequest) GetDuration() string {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return ""
}

func (x *CreateCourseRequest) GetTimezone() string {
	if x != nil && x.Timezone != nil {
		return *x.Timezone
	}
	return ""
}

func (x *CreateCourseRequest) GetThumbnail() string {
	if x != nil && x.Thumbnail != nil {
		return *x.Thumbnail
	}
	return ""
}

func (x *CreateCourseRequest) GetDemoVideoStorage() string {
	if x != nil && x.DemoVideoStorage != nil {
		return *x.DemoVideoStorage
	}
	return ""
}

func (x *CreateCourseRequest) GetDemoVideoSource() string {
	if x != nil && x.DemoVideoSource != nil {
		return *x.DemoVideoSource
	}
	return ""
}

func (x *CreateCourseRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateCourseRequest) GetCapacity() int64 {
	if x != nil && x.Capacity != nil {
		return *x.Capacity
	}
	return 0
}

func (x *CreateCourseRequest) GetPrice() string {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return ""
}

func (x *CreateCourseRequest) GetDiscount() string {
	if x != nil && x.Discount != nil {
		return *x.Discount
	}
	return ""
}

func (x *CreateCourseRequest) GetCertificate() string {
	if x != nil && x.Certificate != nil {
		return *x.Certificate
	}
	return ""
}

func (x *CreateCourseRequest) GetGna() string {
	if x != nil && x.Gna != nil {
		return *x.Gna
	}
	return ""
}

func (x *CreateCourseRequest) GetMessageForReviewer() string {
	if x != nil && x.MessageForReviewer != nil {
		return *x.MessageForReviewer
	}
	return ""
}

func (x *CreateCourseRequest) GetIsApproved() string {
	if x != nil && x.IsApproved != nil {
		return *x.IsApproved
	}
	return ""
}

func (x *CreateCourseRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *CreateCourseRequest) GetCourseLevelId() string {
	if x != nil && x.CourseLevelId != nil {
		return *x.CourseLevelId
	}
	return ""
}

func (x *CreateCourseRequest) GetCourseLanguageId() string {
	if x != nil && x.CourseLanguageId != nil {
		return *x.CourseLanguageId
	}
	return ""
}

func (x *CreateCourseRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

type CreateCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseResponse) Reset() {
	*x = CreateCourseResponse{}
	mi := &file_course_course_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseResponse) ProtoMessage() {}

func (x *CreateCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_course_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseResponse.ProtoReflect.Descriptor instead.
func (*CreateCourseResponse) Descriptor() ([]byte, []int) {
	return file_course_course_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCourseResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *CreateCourseResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DetailCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailCourseRequest) Reset() {
	*x = DetailCourseRequest{}
	mi := &file_course_course_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailCourseRequest) ProtoMessage() {}

func (x *DetailCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_course_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailCourseRequest.ProtoReflect.Descriptor instead.
func (*DetailCourseRequest) Descriptor() ([]byte, []int) {
	return file_course_course_proto_rawDescGZIP(), []int{2}
}

func (x *DetailCourseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DetailCourseRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

type DetailCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Address       *string                `protobuf:"bytes,4,opt,name=address,proto3,oneof" json:"address,omitempty"`
	ImageFileName *string                `protobuf:"bytes,5,opt,name=image_file_name,json=imageFileName,proto3,oneof" json:"image_file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailCourseResponse) Reset() {
	*x = DetailCourseResponse{}
	mi := &file_course_course_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailCourseResponse) ProtoMessage() {}

func (x *DetailCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_course_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailCourseResponse.ProtoReflect.Descriptor instead.
func (*DetailCourseResponse) Descriptor() ([]byte, []int) {
	return file_course_course_proto_rawDescGZIP(), []int{3}
}

func (x *DetailCourseResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DetailCourseResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DetailCourseResponse) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *DetailCourseResponse) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *DetailCourseResponse) GetImageFileName() string {
	if x != nil && x.ImageFileName != nil {
		return *x.ImageFileName
	}
	return ""
}

type EditCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	ImageFileName string                 `protobuf:"bytes,4,opt,name=image_file_name,json=imageFileName,proto3" json:"image_file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCourseRequest) Reset() {
	*x = EditCourseRequest{}
	mi := &file_course_course_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCourseRequest) ProtoMessage() {}

func (x *EditCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_course_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCourseRequest.ProtoReflect.Descriptor instead.
func (*EditCourseRequest) Descriptor() ([]byte, []int) {
	return file_course_course_proto_rawDescGZIP(), []int{4}
}

func (x *EditCourseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EditCourseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EditCourseRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *EditCourseRequest) GetImageFileName() string {
	if x != nil {
		return x.ImageFileName
	}
	return ""
}

type EditCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCourseResponse) Reset() {
	*x = EditCourseResponse{}
	mi := &file_course_course_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCourseResponse) ProtoMessage() {}

func (x *EditCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_course_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCourseResponse.ProtoReflect.Descriptor instead.
func (*EditCourseResponse) Descriptor() ([]byte, []int) {
	return file_course_course_proto_rawDescGZIP(), []int{5}
}

func (x *EditCourseResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *EditCourseResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseRequest) Reset() {
	*x = DeleteCourseRequest{}
	mi := &file_course_course_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseRequest) ProtoMessage() {}

func (x *DeleteCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_course_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseRequest.ProtoReflect.Descriptor instead.
func (*DeleteCourseRequest) Descriptor() ([]byte, []int) {
	return file_course_course_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCourseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseResponse) Reset() {
	*x = DeleteCourseResponse{}
	mi := &file_course_course_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseResponse) ProtoMessage() {}

func (x *DeleteCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_course_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseResponse.ProtoReflect.Descriptor instead.
func (*DeleteCourseResponse) Descriptor() ([]byte, []int) {
	return file_course_course_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCourseResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_course_course_proto protoreflect.FileDescriptor

const file_course_course_proto_rawDesc = "" +
	"\n" +
	"\x13course/course.proto\x12\x06course\x1a\x1acommon/base_response.proto\x1a\x1bbuf/validate/validate.proto\x1a google/protobuf/field_mask.proto\"\xb4\f\n" +
	"\x13CreateCourseRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x02id\x12\x1e\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x12\"\n" +
	"\aaddress\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\xe8\aR\aaddress\x122\n" +
	"\x0fimage_file_name\x18\x04 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\rimageFileName\x12!\n" +
	"\x04slug\x18\x05 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x00R\x04slug\x88\x01\x01\x12.\n" +
	"\vcategory_id\x18\x06 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x01R\n" +
	"categoryId\x88\x01\x01\x12.\n" +
	"\vcourse_type\x18\a \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x02R\n" +
	"courseType\x88\x01\x01\x12#\n" +
	"\x05title\x18\b \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x03R\x05title\x88\x01\x01\x126\n" +
	"\x0fseo_description\x18\t \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x04R\x0eseoDescription\x88\x01\x01\x12)\n" +
	"\bduration\x18\n" +
	" \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x05R\bduration\x88\x01\x01\x12)\n" +
	"\btimezone\x18\v \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x06R\btimezone\x88\x01\x01\x12+\n" +
	"\tthumbnail\x18\f \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\aR\tthumbnail\x88\x01\x01\x12;\n" +
	"\x12demo_video_storage\x18\r \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\bR\x10demoVideoStorage\x88\x01\x01\x129\n" +
	"\x11demo_video_source\x18\x0e \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\tR\x0fdemoVideoSource\x88\x01\x01\x12/\n" +
	"\vdescription\x18\x0f \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\n" +
	"R\vdescription\x88\x01\x01\x12(\n" +
	"\bcapacity\x18\x10 \x01(\x03B\a\xbaH\x04\"\x02(\x00H\vR\bcapacity\x88\x01\x01\x129\n" +
	"\x05price\x18\x11 \x01(\tB\x1e\xbaH\x1br\x192\x17^[0-9]+(\\.[0-9]{1,2})?$H\fR\x05price\x88\x01\x01\x12?\n" +
	"\bdiscount\x18\x12 \x01(\tB\x1e\xbaH\x1br\x192\x17^[0-9]+(\\.[0-9]{1,2})?$H\rR\bdiscount\x88\x01\x01\x12/\n" +
	"\vcertificate\x18\x13 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x0eR\vcertificate\x88\x01\x01\x12\x1f\n" +
	"\x03gna\x18\x14 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x0fR\x03gna\x88\x01\x01\x12?\n" +
	"\x14message_for_reviewer\x18\x15 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x10R\x12messageForReviewer\x88\x01\x01\x12.\n" +
	"\vis_approved\x18\x16 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x11R\n" +
	"isApproved\x88\x01\x01\x12%\n" +
	"\x06status\x18\x17 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x12R\x06status\x88\x01\x01\x125\n" +
	"\x0fcourse_level_id\x18\x18 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x13R\rcourseLevelId\x88\x01\x01\x12;\n" +
	"\x12course_language_id\x18\x19 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x14R\x10courseLanguageId\x88\x01\x01\x12&\n" +
	"\auser_id\x18\x1a \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x15R\x06userId\x88\x01\x01B\a\n" +
	"\x05_slugB\x0e\n" +
	"\f_category_idB\x0e\n" +
	"\f_course_typeB\b\n" +
	"\x06_titleB\x12\n" +
	"\x10_seo_descriptionB\v\n" +
	"\t_durationB\v\n" +
	"\t_timezoneB\f\n" +
	"\n" +
	"_thumbnailB\x15\n" +
	"\x13_demo_video_storageB\x14\n" +
	"\x12_demo_video_sourceB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_capacityB\b\n" +
	"\x06_priceB\v\n" +
	"\t_discountB\x0e\n" +
	"\f_certificateB\x06\n" +
	"\x04_gnaB\x17\n" +
	"\x15_message_for_reviewerB\x0e\n" +
	"\f_is_approvedB\t\n" +
	"\a_statusB\x12\n" +
	"\x10_course_level_idB\x15\n" +
	"\x13_course_language_idB\n" +
	"\n" +
	"\b_user_id\"P\n" +
	"\x14CreateCourseResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"l\n" +
	"\x13DetailCourseRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x02id\x129\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\"\xde\x01\n" +
	"\x14DetailCourseResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\x04 \x01(\tH\x01R\aaddress\x88\x01\x01\x12+\n" +
	"\x0fimage_file_name\x18\x05 \x01(\tH\x02R\rimageFileName\x88\x01\x01B\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_addressB\x12\n" +
	"\x10_image_file_name\"\xa7\x01\n" +
	"\x11EditCourseRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x02id\x12\x1e\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x12\"\n" +
	"\aaddress\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\xe8\aR\aaddress\x122\n" +
	"\x0fimage_file_name\x18\x04 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\rimageFileName\"N\n" +
	"\x12EditCourseResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"1\n" +
	"\x13DeleteCourseRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x02id\"@\n" +
	"\x14DeleteCourseResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base2\xb5\x02\n" +
	"\rCourseService\x12I\n" +
	"\fCreateCourse\x12\x1b.course.CreateCourseRequest\x1a\x1c.course.CreateCourseResponse\x12I\n" +
	"\fDetailCourse\x12\x1b.course.DetailCourseRequest\x1a\x1c.course.DetailCourseResponse\x12C\n" +
	"\n" +
	"EditCourse\x12\x19.course.EditCourseRequest\x1a\x1a.course.EditCourseResponse\x12I\n" +
	"\fDeleteCourse\x12\x1b.course.DeleteCourseRequest\x1a\x1c.course.DeleteCourseResponseB*Z(github.com/abu-umair/be-lms-go/pb/courseb\x06proto3"

var (
	file_course_course_proto_rawDescOnce sync.Once
	file_course_course_proto_rawDescData []byte
)

func file_course_course_proto_rawDescGZIP() []byte {
	file_course_course_proto_rawDescOnce.Do(func() {
		file_course_course_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_course_course_proto_rawDesc), len(file_course_course_proto_rawDesc)))
	})
	return file_course_course_proto_rawDescData
}

var file_course_course_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_course_course_proto_goTypes = []any{
	(*CreateCourseRequest)(nil),   // 0: course.CreateCourseRequest
	(*CreateCourseResponse)(nil),  // 1: course.CreateCourseResponse
	(*DetailCourseRequest)(nil),   // 2: course.DetailCourseRequest
	(*DetailCourseResponse)(nil),  // 3: course.DetailCourseResponse
	(*EditCourseRequest)(nil),     // 4: course.EditCourseRequest
	(*EditCourseResponse)(nil),    // 5: course.EditCourseResponse
	(*DeleteCourseRequest)(nil),   // 6: course.DeleteCourseRequest
	(*DeleteCourseResponse)(nil),  // 7: course.DeleteCourseResponse
	(*common.BaseResponse)(nil),   // 8: common.BaseResponse
	(*fieldmaskpb.FieldMask)(nil), // 9: google.protobuf.FieldMask
}
var file_course_course_proto_depIdxs = []int32{
	8, // 0: course.CreateCourseResponse.base:type_name -> common.BaseResponse
	9, // 1: course.DetailCourseRequest.field_mask:type_name -> google.protobuf.FieldMask
	8, // 2: course.DetailCourseResponse.base:type_name -> common.BaseResponse
	8, // 3: course.EditCourseResponse.base:type_name -> common.BaseResponse
	8, // 4: course.DeleteCourseResponse.base:type_name -> common.BaseResponse
	0, // 5: course.CourseService.CreateCourse:input_type -> course.CreateCourseRequest
	2, // 6: course.CourseService.DetailCourse:input_type -> course.DetailCourseRequest
	4, // 7: course.CourseService.EditCourse:input_type -> course.EditCourseRequest
	6, // 8: course.CourseService.DeleteCourse:input_type -> course.DeleteCourseRequest
	1, // 9: course.CourseService.CreateCourse:output_type -> course.CreateCourseResponse
	3, // 10: course.CourseService.DetailCourse:output_type -> course.DetailCourseResponse
	5, // 11: course.CourseService.EditCourse:output_type -> course.EditCourseResponse
	7, // 12: course.CourseService.DeleteCourse:output_type -> course.DeleteCourseResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_course_course_proto_init() }
func file_course_course_proto_init() {
	if File_course_course_proto != nil {
		return
	}
	file_course_course_proto_msgTypes[0].OneofWrappers = []any{}
	file_course_course_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_course_course_proto_rawDesc), len(file_course_course_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_course_course_proto_goTypes,
		DependencyIndexes: file_course_course_proto_depIdxs,
		MessageInfos:      file_course_course_proto_msgTypes,
	}.Build()
	File_course_course_proto = out.File
	file_course_course_proto_goTypes = nil
	file_course_course_proto_depIdxs = nil
}
