// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: store/store.proto

package store

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	common "github.com/abu-umair/be-lms-go/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	ImageFileName string                 `protobuf:"bytes,4,opt,name=image_file_name,json=imageFileName,proto3" json:"image_file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStoreRequest) Reset() {
	*x = CreateStoreRequest{}
	mi := &file_store_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStoreRequest) ProtoMessage() {}

func (x *CreateStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStoreRequest.ProtoReflect.Descriptor instead.
func (*CreateStoreRequest) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{0}
}

func (x *CreateStoreRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateStoreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateStoreRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateStoreRequest) GetImageFileName() string {
	if x != nil {
		return x.ImageFileName
	}
	return ""
}

type CreateStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStoreResponse) Reset() {
	*x = CreateStoreResponse{}
	mi := &file_store_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStoreResponse) ProtoMessage() {}

func (x *CreateStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStoreResponse.ProtoReflect.Descriptor instead.
func (*CreateStoreResponse) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStoreResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *CreateStoreResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DetailStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailStoreRequest) Reset() {
	*x = DetailStoreRequest{}
	mi := &file_store_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailStoreRequest) ProtoMessage() {}

func (x *DetailStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailStoreRequest.ProtoReflect.Descriptor instead.
func (*DetailStoreRequest) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{2}
}

func (x *DetailStoreRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DetailStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	ImageFileName string                 `protobuf:"bytes,5,opt,name=image_file_name,json=imageFileName,proto3" json:"image_file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailStoreResponse) Reset() {
	*x = DetailStoreResponse{}
	mi := &file_store_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailStoreResponse) ProtoMessage() {}

func (x *DetailStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailStoreResponse.ProtoReflect.Descriptor instead.
func (*DetailStoreResponse) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{3}
}

func (x *DetailStoreResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DetailStoreResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DetailStoreResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DetailStoreResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DetailStoreResponse) GetImageFileName() string {
	if x != nil {
		return x.ImageFileName
	}
	return ""
}

type EditStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	ImageFileName string                 `protobuf:"bytes,4,opt,name=image_file_name,json=imageFileName,proto3" json:"image_file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditStoreRequest) Reset() {
	*x = EditStoreRequest{}
	mi := &file_store_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditStoreRequest) ProtoMessage() {}

func (x *EditStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditStoreRequest.ProtoReflect.Descriptor instead.
func (*EditStoreRequest) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{4}
}

func (x *EditStoreRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EditStoreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EditStoreRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *EditStoreRequest) GetImageFileName() string {
	if x != nil {
		return x.ImageFileName
	}
	return ""
}

type EditStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditStoreResponse) Reset() {
	*x = EditStoreResponse{}
	mi := &file_store_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditStoreResponse) ProtoMessage() {}

func (x *EditStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditStoreResponse.ProtoReflect.Descriptor instead.
func (*EditStoreResponse) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{5}
}

func (x *EditStoreResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *EditStoreResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStoreRequest) Reset() {
	*x = DeleteStoreRequest{}
	mi := &file_store_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStoreRequest) ProtoMessage() {}

func (x *DeleteStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStoreRequest.ProtoReflect.Descriptor instead.
func (*DeleteStoreRequest) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteStoreRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStoreResponse) Reset() {
	*x = DeleteStoreResponse{}
	mi := &file_store_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStoreResponse) ProtoMessage() {}

func (x *DeleteStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStoreResponse.ProtoReflect.Descriptor instead.
func (*DeleteStoreResponse) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteStoreResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_store_store_proto protoreflect.FileDescriptor

const file_store_store_proto_rawDesc = "" +
	"\n" +
	"\x11store/store.proto\x12\x05store\x1a\x1acommon/base_response.proto\x1a\x1bbuf/validate/validate.proto\"\xa8\x01\n" +
	"\x12CreateStoreRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x02id\x12\x1e\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x12\"\n" +
	"\aaddress\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\xe8\aR\aaddress\x122\n" +
	"\x0fimage_file_name\x18\x04 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\rimageFileName\"O\n" +
	"\x13CreateStoreResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"0\n" +
	"\x12DetailStoreRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x02id\"\xa5\x01\n" +
	"\x13DetailStoreResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12&\n" +
	"\x0fimage_file_name\x18\x05 \x01(\tR\rimageFileName\"\xa6\x01\n" +
	"\x10EditStoreRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x02id\x12\x1e\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x12\"\n" +
	"\aaddress\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\xe8\aR\aaddress\x122\n" +
	"\x0fimage_file_name\x18\x04 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\rimageFileName\"M\n" +
	"\x11EditStoreResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"0\n" +
	"\x12DeleteStoreRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x02id\"?\n" +
	"\x13DeleteStoreResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base2\xa0\x02\n" +
	"\fStoreService\x12D\n" +
	"\vCreateStore\x12\x19.store.CreateStoreRequest\x1a\x1a.store.CreateStoreResponse\x12D\n" +
	"\vDetailStore\x12\x19.store.DetailStoreRequest\x1a\x1a.store.DetailStoreResponse\x12>\n" +
	"\tEditStore\x12\x17.store.EditStoreRequest\x1a\x18.store.EditStoreResponse\x12D\n" +
	"\vDeleteStore\x12\x19.store.DeleteStoreRequest\x1a\x1a.store.DeleteStoreResponseB2Z0github.com/abu-umair/be-lms-go/pb/storeb\x06proto3"

var (
	file_store_store_proto_rawDescOnce sync.Once
	file_store_store_proto_rawDescData []byte
)

func file_store_store_proto_rawDescGZIP() []byte {
	file_store_store_proto_rawDescOnce.Do(func() {
		file_store_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_store_store_proto_rawDesc), len(file_store_store_proto_rawDesc)))
	})
	return file_store_store_proto_rawDescData
}

var file_store_store_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_store_store_proto_goTypes = []any{
	(*CreateStoreRequest)(nil),  // 0: store.CreateStoreRequest
	(*CreateStoreResponse)(nil), // 1: store.CreateStoreResponse
	(*DetailStoreRequest)(nil),  // 2: store.DetailStoreRequest
	(*DetailStoreResponse)(nil), // 3: store.DetailStoreResponse
	(*EditStoreRequest)(nil),    // 4: store.EditStoreRequest
	(*EditStoreResponse)(nil),   // 5: store.EditStoreResponse
	(*DeleteStoreRequest)(nil),  // 6: store.DeleteStoreRequest
	(*DeleteStoreResponse)(nil), // 7: store.DeleteStoreResponse
	(*common.BaseResponse)(nil), // 8: common.BaseResponse
}
var file_store_store_proto_depIdxs = []int32{
	8, // 0: store.CreateStoreResponse.base:type_name -> common.BaseResponse
	8, // 1: store.DetailStoreResponse.base:type_name -> common.BaseResponse
	8, // 2: store.EditStoreResponse.base:type_name -> common.BaseResponse
	8, // 3: store.DeleteStoreResponse.base:type_name -> common.BaseResponse
	0, // 4: store.StoreService.CreateStore:input_type -> store.CreateStoreRequest
	2, // 5: store.StoreService.DetailStore:input_type -> store.DetailStoreRequest
	4, // 6: store.StoreService.EditStore:input_type -> store.EditStoreRequest
	6, // 7: store.StoreService.DeleteStore:input_type -> store.DeleteStoreRequest
	1, // 8: store.StoreService.CreateStore:output_type -> store.CreateStoreResponse
	3, // 9: store.StoreService.DetailStore:output_type -> store.DetailStoreResponse
	5, // 10: store.StoreService.EditStore:output_type -> store.EditStoreResponse
	7, // 11: store.StoreService.DeleteStore:output_type -> store.DeleteStoreResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_store_store_proto_init() }
func file_store_store_proto_init() {
	if File_store_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_store_proto_rawDesc), len(file_store_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_store_store_proto_goTypes,
		DependencyIndexes: file_store_store_proto_depIdxs,
		MessageInfos:      file_store_store_proto_msgTypes,
	}.Build()
	File_store_store_proto = out.File
	file_store_store_proto_goTypes = nil
	file_store_store_proto_depIdxs = nil
}
