// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: course_chapter/course_chapter.proto

package course_chapter

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	common "github.com/abu-umair/be-lms-go/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCourseChapterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstructorId  string                 `protobuf:"bytes,1,opt,name=instructor_id,json=instructorId,proto3" json:"instructor_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	OrderChapter  int64                  `protobuf:"varint,4,opt,name=order_chapter,json=orderChapter,proto3" json:"order_chapter,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseChapterRequest) Reset() {
	*x = CreateCourseChapterRequest{}
	mi := &file_course_chapter_course_chapter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseChapterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseChapterRequest) ProtoMessage() {}

func (x *CreateCourseChapterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_chapter_course_chapter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseChapterRequest.ProtoReflect.Descriptor instead.
func (*CreateCourseChapterRequest) Descriptor() ([]byte, []int) {
	return file_course_chapter_course_chapter_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCourseChapterRequest) GetInstructorId() string {
	if x != nil {
		return x.InstructorId
	}
	return ""
}

func (x *CreateCourseChapterRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CreateCourseChapterRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCourseChapterRequest) GetOrderChapter() int64 {
	if x != nil {
		return x.OrderChapter
	}
	return 0
}

func (x *CreateCourseChapterRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateCourseChapterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseChapterResponse) Reset() {
	*x = CreateCourseChapterResponse{}
	mi := &file_course_chapter_course_chapter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseChapterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseChapterResponse) ProtoMessage() {}

func (x *CreateCourseChapterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_chapter_course_chapter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseChapterResponse.ProtoReflect.Descriptor instead.
func (*CreateCourseChapterResponse) Descriptor() ([]byte, []int) {
	return file_course_chapter_course_chapter_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCourseChapterResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *CreateCourseChapterResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DetailCourseChapterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailCourseChapterRequest) Reset() {
	*x = DetailCourseChapterRequest{}
	mi := &file_course_chapter_course_chapter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailCourseChapterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailCourseChapterRequest) ProtoMessage() {}

func (x *DetailCourseChapterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_chapter_course_chapter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailCourseChapterRequest.ProtoReflect.Descriptor instead.
func (*DetailCourseChapterRequest) Descriptor() ([]byte, []int) {
	return file_course_chapter_course_chapter_proto_rawDescGZIP(), []int{2}
}

func (x *DetailCourseChapterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DetailCourseChapterRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

type DetailCourseChapterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	InstructorId  *string                `protobuf:"bytes,3,opt,name=instructor_id,json=instructorId,proto3,oneof" json:"instructor_id,omitempty"`
	CourseId      *string                `protobuf:"bytes,4,opt,name=course_id,json=courseId,proto3,oneof" json:"course_id,omitempty"`
	Title         *string                `protobuf:"bytes,5,opt,name=title,proto3,oneof" json:"title,omitempty"`
	OrderChapter  *int64                 `protobuf:"varint,6,opt,name=order_chapter,json=orderChapter,proto3,oneof" json:"order_chapter,omitempty"`
	Status        *string                `protobuf:"bytes,7,opt,name=status,proto3,oneof" json:"status,omitempty"`
	CreatedAt     *string                `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	CreatedBy     *string                `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3,oneof" json:"created_by,omitempty"`
	DeletedBy     *string                `protobuf:"bytes,10,opt,name=deleted_by,json=deletedBy,proto3,oneof" json:"deleted_by,omitempty"`
	UpdatedAt     *string                `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	UpdatedBy     *string                `protobuf:"bytes,12,opt,name=updated_by,json=updatedBy,proto3,oneof" json:"updated_by,omitempty"`
	DeletedAt     *string                `protobuf:"bytes,13,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailCourseChapterResponse) Reset() {
	*x = DetailCourseChapterResponse{}
	mi := &file_course_chapter_course_chapter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailCourseChapterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailCourseChapterResponse) ProtoMessage() {}

func (x *DetailCourseChapterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_chapter_course_chapter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailCourseChapterResponse.ProtoReflect.Descriptor instead.
func (*DetailCourseChapterResponse) Descriptor() ([]byte, []int) {
	return file_course_chapter_course_chapter_proto_rawDescGZIP(), []int{3}
}

func (x *DetailCourseChapterResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DetailCourseChapterResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DetailCourseChapterResponse) GetInstructorId() string {
	if x != nil && x.InstructorId != nil {
		return *x.InstructorId
	}
	return ""
}

func (x *DetailCourseChapterResponse) GetCourseId() string {
	if x != nil && x.CourseId != nil {
		return *x.CourseId
	}
	return ""
}

func (x *DetailCourseChapterResponse) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *DetailCourseChapterResponse) GetOrderChapter() int64 {
	if x != nil && x.OrderChapter != nil {
		return *x.OrderChapter
	}
	return 0
}

func (x *DetailCourseChapterResponse) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *DetailCourseChapterResponse) GetCreatedAt() string {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return ""
}

func (x *DetailCourseChapterResponse) GetCreatedBy() string {
	if x != nil && x.CreatedBy != nil {
		return *x.CreatedBy
	}
	return ""
}

func (x *DetailCourseChapterResponse) GetDeletedBy() string {
	if x != nil && x.DeletedBy != nil {
		return *x.DeletedBy
	}
	return ""
}

func (x *DetailCourseChapterResponse) GetUpdatedAt() string {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return ""
}

func (x *DetailCourseChapterResponse) GetUpdatedBy() string {
	if x != nil && x.UpdatedBy != nil {
		return *x.UpdatedBy
	}
	return ""
}

func (x *DetailCourseChapterResponse) GetDeletedAt() string {
	if x != nil && x.DeletedAt != nil {
		return *x.DeletedAt
	}
	return ""
}

type EditCourseChapterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InstructorId  string                 `protobuf:"bytes,2,opt,name=instructor_id,json=instructorId,proto3" json:"instructor_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	OrderChapter  int64                  `protobuf:"varint,5,opt,name=order_chapter,json=orderChapter,proto3" json:"order_chapter,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCourseChapterRequest) Reset() {
	*x = EditCourseChapterRequest{}
	mi := &file_course_chapter_course_chapter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCourseChapterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCourseChapterRequest) ProtoMessage() {}

func (x *EditCourseChapterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_chapter_course_chapter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCourseChapterRequest.ProtoReflect.Descriptor instead.
func (*EditCourseChapterRequest) Descriptor() ([]byte, []int) {
	return file_course_chapter_course_chapter_proto_rawDescGZIP(), []int{4}
}

func (x *EditCourseChapterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EditCourseChapterRequest) GetInstructorId() string {
	if x != nil {
		return x.InstructorId
	}
	return ""
}

func (x *EditCourseChapterRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *EditCourseChapterRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EditCourseChapterRequest) GetOrderChapter() int64 {
	if x != nil {
		return x.OrderChapter
	}
	return 0
}

func (x *EditCourseChapterRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type EditCourseChapterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCourseChapterResponse) Reset() {
	*x = EditCourseChapterResponse{}
	mi := &file_course_chapter_course_chapter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCourseChapterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCourseChapterResponse) ProtoMessage() {}

func (x *EditCourseChapterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_chapter_course_chapter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCourseChapterResponse.ProtoReflect.Descriptor instead.
func (*EditCourseChapterResponse) Descriptor() ([]byte, []int) {
	return file_course_chapter_course_chapter_proto_rawDescGZIP(), []int{5}
}

func (x *EditCourseChapterResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *EditCourseChapterResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCourseChapterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseChapterRequest) Reset() {
	*x = DeleteCourseChapterRequest{}
	mi := &file_course_chapter_course_chapter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseChapterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseChapterRequest) ProtoMessage() {}

func (x *DeleteCourseChapterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_chapter_course_chapter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseChapterRequest.ProtoReflect.Descriptor instead.
func (*DeleteCourseChapterRequest) Descriptor() ([]byte, []int) {
	return file_course_chapter_course_chapter_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCourseChapterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCourseChapterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseChapterResponse) Reset() {
	*x = DeleteCourseChapterResponse{}
	mi := &file_course_chapter_course_chapter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseChapterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseChapterResponse) ProtoMessage() {}

func (x *DeleteCourseChapterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_chapter_course_chapter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseChapterResponse.ProtoReflect.Descriptor instead.
func (*DeleteCourseChapterResponse) Descriptor() ([]byte, []int) {
	return file_course_chapter_course_chapter_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCourseChapterResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_course_chapter_course_chapter_proto protoreflect.FileDescriptor

const file_course_chapter_course_chapter_proto_rawDesc = "" +
	"\n" +
	"#course_chapter/course_chapter.proto\x12\x0ecourse_chapter\x1a\x1acommon/base_response.proto\x1a\x1bbuf/validate/validate.proto\x1a google/protobuf/field_mask.proto\"\xe8\x01\n" +
	"\x1aCreateCourseChapterRequest\x12/\n" +
	"\rinstructor_id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\finstructorId\x12'\n" +
	"\tcourse_id\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\bcourseId\x12 \n" +
	"\x05title\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x05title\x12,\n" +
	"\rorder_chapter\x18\x04 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\forderChapter\x12 \n" +
	"\x06status\x18\x05 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\x06status\"W\n" +
	"\x1bCreateCourseChapterResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"s\n" +
	"\x1aDetailCourseChapterRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x02id\x129\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\"\xfe\x04\n" +
	"\x1bDetailCourseChapterResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12(\n" +
	"\rinstructor_id\x18\x03 \x01(\tH\x00R\finstructorId\x88\x01\x01\x12 \n" +
	"\tcourse_id\x18\x04 \x01(\tH\x01R\bcourseId\x88\x01\x01\x12\x19\n" +
	"\x05title\x18\x05 \x01(\tH\x02R\x05title\x88\x01\x01\x12(\n" +
	"\rorder_chapter\x18\x06 \x01(\x03H\x03R\forderChapter\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\a \x01(\tH\x04R\x06status\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_at\x18\b \x01(\tH\x05R\tcreatedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_by\x18\t \x01(\tH\x06R\tcreatedBy\x88\x01\x01\x12\"\n" +
	"\n" +
	"deleted_by\x18\n" +
	" \x01(\tH\aR\tdeletedBy\x88\x01\x01\x12\"\n" +
	"\n" +
	"updated_at\x18\v \x01(\tH\bR\tupdatedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"updated_by\x18\f \x01(\tH\tR\tupdatedBy\x88\x01\x01\x12\"\n" +
	"\n" +
	"deleted_at\x18\r \x01(\tH\n" +
	"R\tdeletedAt\x88\x01\x01B\x10\n" +
	"\x0e_instructor_idB\f\n" +
	"\n" +
	"_course_idB\b\n" +
	"\x06_titleB\x10\n" +
	"\x0e_order_chapterB\t\n" +
	"\a_statusB\r\n" +
	"\v_created_atB\r\n" +
	"\v_created_byB\r\n" +
	"\v_deleted_byB\r\n" +
	"\v_updated_atB\r\n" +
	"\v_updated_byB\r\n" +
	"\v_deleted_at\"\x82\x02\n" +
	"\x18EditCourseChapterRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x02id\x12/\n" +
	"\rinstructor_id\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\finstructorId\x12'\n" +
	"\tcourse_id\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\bcourseId\x12 \n" +
	"\x05title\x18\x04 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x05title\x12,\n" +
	"\rorder_chapter\x18\x05 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\forderChapter\x12 \n" +
	"\x06status\x18\x06 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\x06status\"U\n" +
	"\x19EditCourseChapterResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"8\n" +
	"\x1aDeleteCourseChapterRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x02id\"G\n" +
	"\x1bDeleteCourseChapterResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base2\xd0\x03\n" +
	"\x14CourseChapterService\x12n\n" +
	"\x13CreateCourseChapter\x12*.course_chapter.CreateCourseChapterRequest\x1a+.course_chapter.CreateCourseChapterResponse\x12n\n" +
	"\x13DetailCourseChapter\x12*.course_chapter.DetailCourseChapterRequest\x1a+.course_chapter.DetailCourseChapterResponse\x12h\n" +
	"\x11EditCourseChapter\x12(.course_chapter.EditCourseChapterRequest\x1a).course_chapter.EditCourseChapterResponse\x12n\n" +
	"\x13DeleteCourseChapter\x12*.course_chapter.DeleteCourseChapterRequest\x1a+.course_chapter.DeleteCourseChapterResponseB2Z0github.com/abu-umair/be-lms-go/pb/course_chapterb\x06proto3"

var (
	file_course_chapter_course_chapter_proto_rawDescOnce sync.Once
	file_course_chapter_course_chapter_proto_rawDescData []byte
)

func file_course_chapter_course_chapter_proto_rawDescGZIP() []byte {
	file_course_chapter_course_chapter_proto_rawDescOnce.Do(func() {
		file_course_chapter_course_chapter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_course_chapter_course_chapter_proto_rawDesc), len(file_course_chapter_course_chapter_proto_rawDesc)))
	})
	return file_course_chapter_course_chapter_proto_rawDescData
}

var file_course_chapter_course_chapter_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_course_chapter_course_chapter_proto_goTypes = []any{
	(*CreateCourseChapterRequest)(nil),  // 0: course_chapter.CreateCourseChapterRequest
	(*CreateCourseChapterResponse)(nil), // 1: course_chapter.CreateCourseChapterResponse
	(*DetailCourseChapterRequest)(nil),  // 2: course_chapter.DetailCourseChapterRequest
	(*DetailCourseChapterResponse)(nil), // 3: course_chapter.DetailCourseChapterResponse
	(*EditCourseChapterRequest)(nil),    // 4: course_chapter.EditCourseChapterRequest
	(*EditCourseChapterResponse)(nil),   // 5: course_chapter.EditCourseChapterResponse
	(*DeleteCourseChapterRequest)(nil),  // 6: course_chapter.DeleteCourseChapterRequest
	(*DeleteCourseChapterResponse)(nil), // 7: course_chapter.DeleteCourseChapterResponse
	(*common.BaseResponse)(nil),         // 8: common.BaseResponse
	(*fieldmaskpb.FieldMask)(nil),       // 9: google.protobuf.FieldMask
}
var file_course_chapter_course_chapter_proto_depIdxs = []int32{
	8, // 0: course_chapter.CreateCourseChapterResponse.base:type_name -> common.BaseResponse
	9, // 1: course_chapter.DetailCourseChapterRequest.field_mask:type_name -> google.protobuf.FieldMask
	8, // 2: course_chapter.DetailCourseChapterResponse.base:type_name -> common.BaseResponse
	8, // 3: course_chapter.EditCourseChapterResponse.base:type_name -> common.BaseResponse
	8, // 4: course_chapter.DeleteCourseChapterResponse.base:type_name -> common.BaseResponse
	0, // 5: course_chapter.CourseChapterService.CreateCourseChapter:input_type -> course_chapter.CreateCourseChapterRequest
	2, // 6: course_chapter.CourseChapterService.DetailCourseChapter:input_type -> course_chapter.DetailCourseChapterRequest
	4, // 7: course_chapter.CourseChapterService.EditCourseChapter:input_type -> course_chapter.EditCourseChapterRequest
	6, // 8: course_chapter.CourseChapterService.DeleteCourseChapter:input_type -> course_chapter.DeleteCourseChapterRequest
	1, // 9: course_chapter.CourseChapterService.CreateCourseChapter:output_type -> course_chapter.CreateCourseChapterResponse
	3, // 10: course_chapter.CourseChapterService.DetailCourseChapter:output_type -> course_chapter.DetailCourseChapterResponse
	5, // 11: course_chapter.CourseChapterService.EditCourseChapter:output_type -> course_chapter.EditCourseChapterResponse
	7, // 12: course_chapter.CourseChapterService.DeleteCourseChapter:output_type -> course_chapter.DeleteCourseChapterResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_course_chapter_course_chapter_proto_init() }
func file_course_chapter_course_chapter_proto_init() {
	if File_course_chapter_course_chapter_proto != nil {
		return
	}
	file_course_chapter_course_chapter_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_course_chapter_course_chapter_proto_rawDesc), len(file_course_chapter_course_chapter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_course_chapter_course_chapter_proto_goTypes,
		DependencyIndexes: file_course_chapter_course_chapter_proto_depIdxs,
		MessageInfos:      file_course_chapter_course_chapter_proto_msgTypes,
	}.Build()
	File_course_chapter_course_chapter_proto = out.File
	file_course_chapter_course_chapter_proto_goTypes = nil
	file_course_chapter_course_chapter_proto_depIdxs = nil
}
