// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: course_chapter/course_chapter.proto

package course_chapter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CourseChapterService_CreateCourseChapter_FullMethodName = "/course_chapter.CourseChapterService/CreateCourseChapter"
	CourseChapterService_DetailCourseChapter_FullMethodName = "/course_chapter.CourseChapterService/DetailCourseChapter"
	CourseChapterService_EditCourseChapter_FullMethodName   = "/course_chapter.CourseChapterService/EditCourseChapter"
	CourseChapterService_DeleteCourseChapter_FullMethodName = "/course_chapter.CourseChapterService/DeleteCourseChapter"
)

// CourseChapterServiceClient is the client API for CourseChapterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CourseChapterServiceClient interface {
	CreateCourseChapter(ctx context.Context, in *CreateCourseChapterRequest, opts ...grpc.CallOption) (*CreateCourseChapterResponse, error)
	DetailCourseChapter(ctx context.Context, in *DetailCourseChapterRequest, opts ...grpc.CallOption) (*DetailCourseChapterResponse, error)
	EditCourseChapter(ctx context.Context, in *EditCourseChapterRequest, opts ...grpc.CallOption) (*EditCourseChapterResponse, error)
	DeleteCourseChapter(ctx context.Context, in *DeleteCourseChapterRequest, opts ...grpc.CallOption) (*DeleteCourseChapterResponse, error)
}

type courseChapterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCourseChapterServiceClient(cc grpc.ClientConnInterface) CourseChapterServiceClient {
	return &courseChapterServiceClient{cc}
}

func (c *courseChapterServiceClient) CreateCourseChapter(ctx context.Context, in *CreateCourseChapterRequest, opts ...grpc.CallOption) (*CreateCourseChapterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCourseChapterResponse)
	err := c.cc.Invoke(ctx, CourseChapterService_CreateCourseChapter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseChapterServiceClient) DetailCourseChapter(ctx context.Context, in *DetailCourseChapterRequest, opts ...grpc.CallOption) (*DetailCourseChapterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetailCourseChapterResponse)
	err := c.cc.Invoke(ctx, CourseChapterService_DetailCourseChapter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseChapterServiceClient) EditCourseChapter(ctx context.Context, in *EditCourseChapterRequest, opts ...grpc.CallOption) (*EditCourseChapterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditCourseChapterResponse)
	err := c.cc.Invoke(ctx, CourseChapterService_EditCourseChapter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseChapterServiceClient) DeleteCourseChapter(ctx context.Context, in *DeleteCourseChapterRequest, opts ...grpc.CallOption) (*DeleteCourseChapterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCourseChapterResponse)
	err := c.cc.Invoke(ctx, CourseChapterService_DeleteCourseChapter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CourseChapterServiceServer is the server API for CourseChapterService service.
// All implementations must embed UnimplementedCourseChapterServiceServer
// for forward compatibility.
type CourseChapterServiceServer interface {
	CreateCourseChapter(context.Context, *CreateCourseChapterRequest) (*CreateCourseChapterResponse, error)
	DetailCourseChapter(context.Context, *DetailCourseChapterRequest) (*DetailCourseChapterResponse, error)
	EditCourseChapter(context.Context, *EditCourseChapterRequest) (*EditCourseChapterResponse, error)
	DeleteCourseChapter(context.Context, *DeleteCourseChapterRequest) (*DeleteCourseChapterResponse, error)
	mustEmbedUnimplementedCourseChapterServiceServer()
}

// UnimplementedCourseChapterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCourseChapterServiceServer struct{}

func (UnimplementedCourseChapterServiceServer) CreateCourseChapter(context.Context, *CreateCourseChapterRequest) (*CreateCourseChapterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCourseChapter not implemented")
}
func (UnimplementedCourseChapterServiceServer) DetailCourseChapter(context.Context, *DetailCourseChapterRequest) (*DetailCourseChapterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetailCourseChapter not implemented")
}
func (UnimplementedCourseChapterServiceServer) EditCourseChapter(context.Context, *EditCourseChapterRequest) (*EditCourseChapterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditCourseChapter not implemented")
}
func (UnimplementedCourseChapterServiceServer) DeleteCourseChapter(context.Context, *DeleteCourseChapterRequest) (*DeleteCourseChapterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCourseChapter not implemented")
}
func (UnimplementedCourseChapterServiceServer) mustEmbedUnimplementedCourseChapterServiceServer() {}
func (UnimplementedCourseChapterServiceServer) testEmbeddedByValue()                              {}

// UnsafeCourseChapterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CourseChapterServiceServer will
// result in compilation errors.
type UnsafeCourseChapterServiceServer interface {
	mustEmbedUnimplementedCourseChapterServiceServer()
}

func RegisterCourseChapterServiceServer(s grpc.ServiceRegistrar, srv CourseChapterServiceServer) {
	// If the following call pancis, it indicates UnimplementedCourseChapterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CourseChapterService_ServiceDesc, srv)
}

func _CourseChapterService_CreateCourseChapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCourseChapterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseChapterServiceServer).CreateCourseChapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseChapterService_CreateCourseChapter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseChapterServiceServer).CreateCourseChapter(ctx, req.(*CreateCourseChapterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseChapterService_DetailCourseChapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetailCourseChapterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseChapterServiceServer).DetailCourseChapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseChapterService_DetailCourseChapter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseChapterServiceServer).DetailCourseChapter(ctx, req.(*DetailCourseChapterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseChapterService_EditCourseChapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditCourseChapterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseChapterServiceServer).EditCourseChapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseChapterService_EditCourseChapter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseChapterServiceServer).EditCourseChapter(ctx, req.(*EditCourseChapterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseChapterService_DeleteCourseChapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCourseChapterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseChapterServiceServer).DeleteCourseChapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseChapterService_DeleteCourseChapter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseChapterServiceServer).DeleteCourseChapter(ctx, req.(*DeleteCourseChapterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CourseChapterService_ServiceDesc is the grpc.ServiceDesc for CourseChapterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CourseChapterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "course_chapter.CourseChapterService",
	HandlerType: (*CourseChapterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCourseChapter",
			Handler:    _CourseChapterService_CreateCourseChapter_Handler,
		},
		{
			MethodName: "DetailCourseChapter",
			Handler:    _CourseChapterService_DetailCourseChapter_Handler,
		},
		{
			MethodName: "EditCourseChapter",
			Handler:    _CourseChapterService_EditCourseChapter_Handler,
		},
		{
			MethodName: "DeleteCourseChapter",
			Handler:    _CourseChapterService_DeleteCourseChapter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "course_chapter/course_chapter.proto",
}
